controller_list:
  - name: fake_cyton1500_group_controller
    joints:
      - shoulder_roll_joint
      - shoulder_pitch_joint
      - shoulder_yaw_joint
      - elbow_pitch_joint
      - elbow_yaw_joint
      - wrist_pitch_joint
      - wrist_roll_joint